# Generated by Django 6.0.6 on 2026-06-08 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField()),
                ('current_index', models.IntegerField(default=0)),
                ('answers', models.TextField(default='')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.resume')),
            ],
        ),
    ]
